import { Product, Template } from './types';

export const SAMPLE_PRODUCTS: Product[] = [
  { id: 'prod_001', name: 'Rice', description: 'Long-grain white rice.' },
  { id: 'prod_002', name: 'White sugar', description: 'Granulated white sugar.' },
  { id: 'prod_003', name: 'Brown sugar', description: 'Light brown sugar.' },
  { id: 'prod_004', name: 'Salt', description: 'Iodized table salt.' },
  { id: 'prod_005', name: 'Wheat flour', description: 'All-purpose wheat flour.' },
  { id: 'prod_006', name: 'Cornmeal', description: 'Fine yellow cornmeal.' },
  { id: 'prod_007', name: 'Spaghetti', description: 'Classic spaghetti pasta.' },
  { id: 'prod_008', name: 'Macaroni', description: 'Elbow macaroni pasta.' },
  { id: 'prod_009', name: 'Instant Noodles', description: 'Pack of instant noodles.' },
  { id: 'prod_010', name: 'Ramen Noodles', description: 'Pack of ramen noodles.' },
  { id: 'prod_011', name: 'Red Lentils', description: 'Dried red lentils.' },
  { id: 'prod_012', name: 'Green Lentils', description: 'Dried green lentils.' },
  { id: 'prod_013', name: 'Chickpeas', description: 'Dried chickpeas (garbanzo beans).' },
  { id: 'prod_014', name: 'Black beans', description: 'Dried black beans.' },
  { id: 'prod_015', name: 'Kidney beans', description: 'Dried red kidney beans.' },
  { id: 'prod_016', name: 'Pinto beans', description: 'Dried pinto beans.' },
  { id: 'prod_017', name: 'Split peas', description: 'Dried green split peas.' },
  { id: 'prod_018', name: 'Rolled Oats', description: 'Old-fashioned rolled oats.' },
  { id: 'prod_019', name: 'Instant Oats', description: 'Packet of instant oatmeal.' },
  { id: 'prod_020', name: 'Barley', description: 'Pearled barley.' },
  { id: 'prod_021', name: 'Quinoa', description: 'Organic white quinoa.' },
  { id: 'prod_022', name: 'Couscous', description: 'Moroccan couscous.' },
  { id: 'prod_023', name: 'Polenta', description: 'Instant polenta corn grits.' },
  { id: 'prod_024', name: 'Bulgur wheat', description: 'Fine bulgur wheat.' },
  { id: 'prod_025', name: 'Semolina', description: 'Semolina flour for pasta.' },
  { id: 'prod_026', name: 'Baking powder', description: 'Double-acting baking powder.' },
  { id: 'prod_027', name: 'Baking soda', description: 'Pure baking soda.' },
  { id: 'prod_028', name: 'Yeast (dry active)', description: 'Packets of dry active yeast.' },
  { id: 'prod_029', name: 'Dried milk powder', description: 'Instant non-fat dry milk powder.' },
  { id: 'prod_030', name: 'Coffee beans', description: 'Whole bean medium roast coffee.' },
  { id: 'prod_031', name: 'Tea bags', description: 'Box of black tea bags.' },
  { id: 'prod_032', name: 'Raisins', description: 'Sun-dried raisins.' },
  { id: 'prod_033', name: 'Dried apricots', description: 'Sweet dried apricots.' },
  { id: 'prod_034', name: 'Dates (dried)', description: 'Pitted Medjool dates.' },
  { id: 'prod_035', name: 'Prunes', description: 'Pitted dried plums.' },
  { id: 'prod_036', name: 'Dried cranberries', description: 'Sweetened dried cranberries.' },
  { id: 'prod_037', name: 'Raw Almonds', description: 'Whole raw almonds.' },
  { id: 'prod_038', name: 'Roasted Almonds', description: 'Lightly salted roasted almonds.' },
  { id: 'prod_039', name: 'Peanuts', description: 'Roasted and salted peanuts.' },
  { id: 'prod_040', name: 'Cashews', description: 'Roasted and salted cashews.' },
  { id: 'prod_041', name: 'Walnuts', description: 'Raw walnut halves.' },
  { id: 'prod_042', name: 'Sunflower seeds', description: 'Roasted and salted sunflower seeds.' },
  { id: 'prod_043', name: 'Pumpkin seeds', description: 'Roasted pumpkin seeds (pepitas).' },
  { id: 'prod_044', name: 'Spaghetti sauce mix (dry)', description: 'Dry mix for spaghetti sauce.' },
  { id: 'prod_045', name: 'Dried soup mix', description: 'Noodle soup mix packet.' },
  { id: 'prod_046', name: 'Dehydrated carrots', description: 'Dried carrot pieces.' },
  { id: 'prod_047', name: 'Dehydrated peas', description: 'Dried green peas.' },
  { id: 'prod_048', name: 'Dried mushrooms', description: 'Assorted dried mushrooms.' },
  { id: 'prod_049', name: 'Dried seaweed', description: 'Roasted seaweed snacks (nori).' },
  { id: 'prod_050', name: 'Soy protein (TVP)', description: 'Textured vegetable protein.' },
  { id: 'prod_051', name: 'Breadcrumbs (dry)', description: 'Plain dry breadcrumbs.' },
  { id: 'prod_052', name: 'Cornstarch', description: 'Pure cornstarch.' },
  { id: 'prod_053', name: 'Instant mashed potatoes', description: 'Flakes for instant mashed potatoes.' },
  { id: 'prod_054', name: 'Dry soup base (bouillon)', description: 'Chicken flavor bouillon cubes.' },
  { id: 'prod_055', name: 'Ground Cumin', description: 'Ground cumin spice.' },
  { id: 'prod_056', name: 'Turmeric', description: 'Ground turmeric spice.' },
  { id: 'prod_057', name: 'Chili Powder', description: 'Classic chili powder blend.' },
];

export const DEFAULT_TEMPLATE: Template = {
  id: 'template_default',
  name: 'Default Modern',
  isDefault: true,
  accentColor: '#f97316', // Corresponds to 'primary' color in Tailwind config
  defaultNotes: 'Thank you for your business! Payment is due within 30 days.',
  layout: 'modern',
};

export const DEFAULT_APP_ICON = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTkyIiBoZWlnaHQ9IjE5MiIgdmlld0JveD0iMCAwIDE5MiAxOTIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iOTYiIGN5PSI5NiIgcj0iOTYiIGZpbGw9IiNmOTczMTYiLz48dGV4dCB4PSI5NiIgeT0iMTA1IiBmb250LWZhbWlseT0iQXJpYWwsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iNDAiIGZpbGw9IndoaXRlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBkb21pbmFudC1iYXNlbGluZT0ibWlkZGxlIj5JTlY8L3RleHQ+PC9zdmc+';
